# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0e\x61ivoice.common\",\n\tDialogRef\x12\x11\n\tdialog_id\x18\x01 \x01(\t\x12\x0c\n\x04turn\x18\x02 \x01(\x05\"\x1c\n\tTimestamp\x12\x0f\n\x07iso8601\x18\x01 \x01(\t\"}\n\rServiceStatus\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\x12\x16\n\x0estatus_message\x18\x03 \x01(\t\x12-\n\nlast_check\x18\x04 \x01(\x0b\x32\x19.aivoice.common.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIALOGREF']._serialized_start=32
  _globals['_DIALOGREF']._serialized_end=76
  _globals['_TIMESTAMP']._serialized_start=78
  _globals['_TIMESTAMP']._serialized_end=106
  _globals['_SERVICESTATUS']._serialized_start=108
  _globals['_SERVICESTATUS']._serialized_end=233
# @@protoc_insertion_point(module_scope)
