# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kwd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kwd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tkwd.proto\x12\x0b\x61ivoice.kwd\x1a\x0c\x63ommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"g\n\tKwdConfig\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x1c\n\x14\x63onfidence_threshold\x18\x02 \x01(\x02\x12\x13\n\x0b\x63ooldown_ms\x18\x03 \x01(\x05\x12\x13\n\x0byes_phrases\x18\x04 \x03(\t\"5\n\x11\x43onfigureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"R\n\x08KwdEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\tdialog_id\x18\x04 \x01(\t2\xfd\x01\n\nKwdService\x12\x43\n\tConfigure\x12\x16.aivoice.kwd.KwdConfig\x1a\x1e.aivoice.kwd.ConfigureResponse\x12\x37\n\x05Start\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x36\n\x04Stop\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x39\n\x06\x45vents\x12\x16.google.protobuf.Empty\x1a\x15.aivoice.kwd.KwdEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kwd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KWDCONFIG']._serialized_start=69
  _globals['_KWDCONFIG']._serialized_end=172
  _globals['_CONFIGURERESPONSE']._serialized_start=174
  _globals['_CONFIGURERESPONSE']._serialized_end=227
  _globals['_KWDEVENT']._serialized_start=229
  _globals['_KWDEVENT']._serialized_end=311
  _globals['_KWDSERVICE']._serialized_start=314
  _globals['_KWDSERVICE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
