# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loader.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'loader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cloader.proto\x12\x0e\x61ivoice.loader\x1a\x0c\x63ommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\x13StartServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"E\n\x14StartServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x05\"*\n\x12StopServiceRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\"7\n\x13StopServiceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8d\x01\n\x0fGetPidsResponse\x12\x46\n\x0cservice_pids\x18\x01 \x03(\x0b\x32\x30.aivoice.loader.GetPidsResponse.ServicePidsEntry\x1a\x32\n\x10ServicePidsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"W\n\rWakeWordEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x11\n\tdialog_id\x18\x04 \x01(\t\"C\n\x13\x44ialogCompleteEvent\x12\x11\n\tdialog_id\x18\x01 \x01(\t\x12\x19\n\x11\x63ompletion_reason\x18\x02 \x01(\t2\xa4\x03\n\rLoaderService\x12Y\n\x0cStartService\x12#.aivoice.loader.StartServiceRequest\x1a$.aivoice.loader.StartServiceResponse\x12V\n\x0bStopService\x12\".aivoice.loader.StopServiceRequest\x1a#.aivoice.loader.StopServiceResponse\x12\x42\n\x07GetPids\x12\x16.google.protobuf.Empty\x1a\x1f.aivoice.loader.GetPidsResponse\x12G\n\x0eHandleWakeWord\x12\x1d.aivoice.loader.WakeWordEvent\x1a\x16.google.protobuf.Empty\x12S\n\x14HandleDialogComplete\x12#.aivoice.loader.DialogCompleteEvent\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPIDSRESPONSE_SERVICEPIDSENTRY']._loaded_options = None
  _globals['_GETPIDSRESPONSE_SERVICEPIDSENTRY']._serialized_options = b'8\001'
  _globals['_STARTSERVICEREQUEST']._serialized_start=75
  _globals['_STARTSERVICEREQUEST']._serialized_end=118
  _globals['_STARTSERVICERESPONSE']._serialized_start=120
  _globals['_STARTSERVICERESPONSE']._serialized_end=189
  _globals['_STOPSERVICEREQUEST']._serialized_start=191
  _globals['_STOPSERVICEREQUEST']._serialized_end=233
  _globals['_STOPSERVICERESPONSE']._serialized_start=235
  _globals['_STOPSERVICERESPONSE']._serialized_end=290
  _globals['_GETPIDSRESPONSE']._serialized_start=293
  _globals['_GETPIDSRESPONSE']._serialized_end=434
  _globals['_GETPIDSRESPONSE_SERVICEPIDSENTRY']._serialized_start=384
  _globals['_GETPIDSRESPONSE_SERVICEPIDSENTRY']._serialized_end=434
  _globals['_WAKEWORDEVENT']._serialized_start=436
  _globals['_WAKEWORDEVENT']._serialized_end=523
  _globals['_DIALOGCOMPLETEEVENT']._serialized_start=525
  _globals['_DIALOGCOMPLETEEVENT']._serialized_end=592
  _globals['_LOADERSERVICE']._serialized_start=595
  _globals['_LOADERSERVICE']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
