# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import loader_pb2 as loader__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in loader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoaderServiceStub(object):
    """Loader service for managing service lifecycle and dialog coordination
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartService = channel.unary_unary(
                '/aivoice.loader.LoaderService/StartService',
                request_serializer=loader__pb2.StartServiceRequest.SerializeToString,
                response_deserializer=loader__pb2.StartServiceResponse.FromString,
                _registered_method=True)
        self.StopService = channel.unary_unary(
                '/aivoice.loader.LoaderService/StopService',
                request_serializer=loader__pb2.StopServiceRequest.SerializeToString,
                response_deserializer=loader__pb2.StopServiceResponse.FromString,
                _registered_method=True)
        self.GetPids = channel.unary_unary(
                '/aivoice.loader.LoaderService/GetPids',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=loader__pb2.GetPidsResponse.FromString,
                _registered_method=True)
        self.HandleWakeWord = channel.unary_unary(
                '/aivoice.loader.LoaderService/HandleWakeWord',
                request_serializer=loader__pb2.WakeWordEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HandleDialogComplete = channel.unary_unary(
                '/aivoice.loader.LoaderService/HandleDialogComplete',
                request_serializer=loader__pb2.DialogCompleteEvent.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class LoaderServiceServicer(object):
    """Loader service for managing service lifecycle and dialog coordination
    """

    def StartService(self, request, context):
        """Service management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPids(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleWakeWord(self, request, context):
        """Dialog management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleDialogComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartService': grpc.unary_unary_rpc_method_handler(
                    servicer.StartService,
                    request_deserializer=loader__pb2.StartServiceRequest.FromString,
                    response_serializer=loader__pb2.StartServiceResponse.SerializeToString,
            ),
            'StopService': grpc.unary_unary_rpc_method_handler(
                    servicer.StopService,
                    request_deserializer=loader__pb2.StopServiceRequest.FromString,
                    response_serializer=loader__pb2.StopServiceResponse.SerializeToString,
            ),
            'GetPids': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPids,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=loader__pb2.GetPidsResponse.SerializeToString,
            ),
            'HandleWakeWord': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleWakeWord,
                    request_deserializer=loader__pb2.WakeWordEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HandleDialogComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleDialogComplete,
                    request_deserializer=loader__pb2.DialogCompleteEvent.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aivoice.loader.LoaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aivoice.loader.LoaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoaderService(object):
    """Loader service for managing service lifecycle and dialog coordination
    """

    @staticmethod
    def StartService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivoice.loader.LoaderService/StartService',
            loader__pb2.StartServiceRequest.SerializeToString,
            loader__pb2.StartServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivoice.loader.LoaderService/StopService',
            loader__pb2.StopServiceRequest.SerializeToString,
            loader__pb2.StopServiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivoice.loader.LoaderService/GetPids',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            loader__pb2.GetPidsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleWakeWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivoice.loader.LoaderService/HandleWakeWord',
            loader__pb2.WakeWordEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleDialogComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivoice.loader.LoaderService/HandleDialogComplete',
            loader__pb2.DialogCompleteEvent.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
