# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clogger.proto\x12\x0e\x61ivoice.logger\x1a\x1bgoogle/protobuf/empty.proto\"]\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\r\n\x05\x65vent\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\t\"R\n\x0b\x44ialogEntry\x12\x11\n\tdialog_id\x18\x01 \x01(\t\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"=\n\x11NewDialogResponse\x12\x11\n\tdialog_id\x18\x01 \x01(\t\x12\x15\n\rlog_file_path\x18\x02 \x01(\t2\xd9\x01\n\rLoggerService\x12<\n\x08WriteApp\x12\x18.aivoice.logger.LogEntry\x1a\x16.google.protobuf.Empty\x12\x42\n\x0bWriteDialog\x12\x1b.aivoice.logger.DialogEntry\x1a\x16.google.protobuf.Empty\x12\x46\n\tNewDialog\x12\x16.google.protobuf.Empty\x1a!.aivoice.logger.NewDialogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=61
  _globals['_LOGENTRY']._serialized_end=154
  _globals['_DIALOGENTRY']._serialized_start=156
  _globals['_DIALOGENTRY']._serialized_end=238
  _globals['_NEWDIALOGRESPONSE']._serialized_start=240
  _globals['_NEWDIALOGRESPONSE']._serialized_end=301
  _globals['_LOGGERSERVICE']._serialized_start=304
  _globals['_LOGGERSERVICE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
