# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x0b\x61ivoice.stt\x1a\x0c\x63ommon.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n\tSttConfig\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x1a\n\x12vad_end_silence_ms\x18\x03 \x01(\x05\x12\x19\n\x11max_recording_sec\x18\x04 \x01(\x05\x12\x13\n\x0b\x61\x65\x63_enabled\x18\x05 \x01(\x08\x12\x13\n\x0b\x61\x65\x63_backend\x18\x06 \x01(\t\"5\n\x11\x43onfigureResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\tSttResult\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2\x88\x02\n\nSttService\x12\x43\n\tConfigure\x12\x16.aivoice.stt.SttConfig\x1a\x1e.aivoice.stt.ConfigureResponse\x12:\n\x05Start\x12\x19.aivoice.common.DialogRef\x1a\x16.google.protobuf.Empty\x12\x39\n\x04Stop\x12\x19.aivoice.common.DialogRef\x1a\x16.google.protobuf.Empty\x12>\n\x07Results\x12\x19.aivoice.common.DialogRef\x1a\x16.aivoice.stt.SttResult0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STTCONFIG']._serialized_start=70
  _globals['_STTCONFIG']._serialized_end=209
  _globals['_CONFIGURERESPONSE']._serialized_start=211
  _globals['_CONFIGURERESPONSE']._serialized_end=264
  _globals['_STTRESULT']._serialized_start=266
  _globals['_STTRESULT']._serialized_end=325
  _globals['_STTSERVICE']._serialized_start=328
  _globals['_STTSERVICE']._serialized_end=592
# @@protoc_insertion_point(module_scope)
